socialaxy_chat/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import log_in, log_out, sign_up, user_list, thread_view, call_view, profile_view, update_profile

urlpatterns = [
    url(r'^login$', log_in, name='login'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^signup$', sign_up, name='signup'),
    url(r'^$', user_list, name='user_list'),
    url(r'^user/(?P<username>.+)$', profile_view, name='user'),
    url(r'^chat/(?P<username>.+)$', thread_view, name='chat'),
    url(r'^thread/(?P<thread_id>.+)$', thread_view, name='thread'),
    url(r'^call/(?P<username>.+)$', call_view, name='call'),
    url(r'^update-profile$', update_profile, name='update_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

socialaxy_site/socialaxy_chat/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import log_in, log_out, sign_up, user_list, thread_view, profile_view, update_profile

urlpatterns = [
    url(r'^login$', log_in, name='login'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^signup$', sign_up, name='signup'),
    url(r'^$', user_list, name='user_list'),
    url(r'^user/(?P<username>.+)$', profile_view, name='user'),
    url(r'^chat/(?P<username>.+)$', thread_view, name='chat'),
    url(r'^thread/(?P<thread_id>.+)$', thread_view, name='thread'),
    url(r'^update-profile$', update_profile, name='update_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

socialaxy_site/socialaxy_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('socialaxy_chat.urls', namespace='socialaxy_chat')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

socialaxy_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('socialaxy_chat.urls', namespace='socialaxy_chat')),
    url(r'^', include('socialaxy_coming_soon_page.urls', namespace='socialaxy_coming_soon')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

socialaxy_site/socialaxy_chat/models.py
import datetime

from django.conf import settings
from django.db import models
from django.core.cache import cache
from channels.binding.websockets import WebsocketBinding


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='profile')
    avatar = models.ImageField(
        upload_to='avatars/',
        default='avatars/no-avatar.png'
    )

    def last_seen(self):
        return cache.get('seen_%s' % self.user.username)

    def online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            return now < self.last_seen() + datetime.timedelta(seconds=settings.USER_ONLINE_TIMEOUT)

        return False

    def __str__(self):
        return u'%s' % (
            self.user.username,
        )


class Thread(models.Model):
    name = models.CharField(max_length=255)
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='threads'
    )
    last_message = models.DateTimeField(null=True)

    def __str__(self):
        return u'%s' % (
            self.name,
        )


class UnreadThread(models.Model):
    thread = models.ForeignKey(Thread)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='unread_thread'
    )
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return u'%s:%s' % (
            self.thread.name,
            self.user.username,
        )


class Message(models.Model):
    thread = models.ForeignKey(Thread, related_name='messages')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.thread.last_message = datetime.datetime.now()
        self.thread.save()
        super(Message, self).save(force_insert=False, force_update=False,
                                  using=None, update_fields=None)

    def __str__(self):
        return u'%s: %s' % (
            self.user.username,
            self.text[:100],
        )


class MessageBinding(WebsocketBinding):
    model = Message
    stream = 'messages'
    fields = ['__all__']

    @classmethod
    def group_names(cls, instance):
        return ['thread-%s' % instance.thread.pk]

    def has_permission(self, user, action, pk):
        return user in self.users

socialaxy_site/socialaxy_chat/forms.py
from django import forms
from .models import Profile


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar',)

socialaxy_chat/views.py
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from django.http import JsonResponse, HttpResponseRedirect, Http404
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from .models import Profile, Thread, UnreadThread, Message
from .forms import AvatarForm

User = get_user_model()


@login_required
def user_list(request):
    """User list."""
    users = User.objects.exclude(id=request.user.id).select_related('profile')
    for user in users:
        try:
            user.status = user.profile.online()
        except Profile.DoesNotExist:
            Profile.objects.get_or_create(user=user)
            user.status = False

    return render(request, 'socialaxy_chat/user_list.html', {'users': users})


@login_required
def profile_view(request, username):
    """User profile."""
    user = get_object_or_404(User, username=username)
    form = AvatarForm(data=request.POST)

    return render(request, 'socialaxy_chat/profile.html', {
        'profile_user': user,
        'is_current_user': user == request.user,
        'form': form,
    })


@login_required
def thread_view(request, username=None, thread_id=None):
    """Thread page."""
    interlocutor = None
    if username:
        interlocutor = get_object_or_404(User, username=username)
        thread = Thread.objects \
            .annotate(count=Count('users')) \
            .filter(users=request.user) \
            .filter(users=interlocutor) \
            .filter(count=2) \
            .first()
        if not thread:
            thread = Thread(name=', '.join([request.user.username, username]))
            thread.save()
            thread.users.add(request.user, interlocutor)
    elif thread_id:
        thread = get_object_or_404(Thread, pk=thread_id)
    else:
        # username or thread_id should be passed.
        raise Http404

    # The user visited this tread - delete user's unread thread.
    UnreadThread.objects.filter(thread=thread, user=request.user).delete()

    users = {}
    for user in thread.users.all():
        profile, _ = Profile.objects.get_or_create(user=user)
        users[user.pk] = {
            'username': user.username,
            'avatar': profile.avatar.url,
        }

    messages = Message.objects.select_related('user').filter(thread=thread) \
                   .order_by('date')[:50]
    for message in messages:
        if message.user.pk not in users:
            try:
                avatar = message.user.profile.avatar.url
            except Profile.DoesNotExist:
                # If there no user profile - create it.
                profile, _ = Profile.objects.get_or_create(user=message.user)
                avatar = profile.avatar.url

            users[message.user.pk] = {
                'username': message.user.username,
                'avatar': avatar,
            }
    for message in messages:
        message.avatar = users[message.user.pk]['avatar']

    return render(request, 'socialaxy_chat/thread.html', {
        'thread': thread,
        'messages': messages,
        'users': users,
        'interlocutor': interlocutor,
    })


@login_required
def call_view(request, username):
    """Call page."""
    interlocutor = get_object_or_404(User, username=username)

    return render(request, 'socialaxy_chat/call.html', {
        'interlocutor': interlocutor,
    })


@login_required
def update_profile(request):
    """Update user."""
    if request.method == 'POST':
        avatar = request.FILES.get('avatar', '')
        if avatar:
            profile = get_object_or_404(Profile, user=request.user)
            form = AvatarForm(request.POST, request.FILES, instance=profile)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            allowed_fields = ['first_name', 'last_name', 'email']
            field = request.POST.get('name', '')
            value = request.POST.get('value', '')
            if field and field in allowed_fields:
                setattr(request.user, field, value)
                try:
                    request.user.clean_fields()
                    request.user.save()
                    return JsonResponse({'success': True})
                except ValidationError as e:
                    return JsonResponse(
                        ', '.join(e.message_dict[field]),
                        safe=False,
                        status=422
                    )

    return JsonResponse(
        _("You can't change this field"),
        safe=False,
        status=403
    )


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('socialaxy_chat:user_list'))

    return render(request, 'socialaxy_chat/login.html', {'form': form})


@login_required
def log_out(request):
    logout(request)
    return redirect(reverse('socialaxy_chat:login'))


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)

            return redirect(reverse('socialaxy_chat:user_list'))

    return render(request, 'socialaxy_chat/signup.html', {'form': form})

socialaxy_site/socialaxy_chat/views.py
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from django.http import JsonResponse, HttpResponseRedirect, Http404
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from .models import Profile, Thread, UnreadThread, Message
from .forms import AvatarForm

User = get_user_model()


@login_required
def user_list(request):
    """User list."""
    users = User.objects.exclude(id=request.user.id).select_related('profile')
    for user in users:
        try:
            user.status = user.profile.online()
        except Profile.DoesNotExist:
            Profile.objects.get_or_create(user=user)
            user.status = False

    return render(request, 'socialaxy_chat/user_list.html', {'users': users})


@login_required
def profile_view(request, username):
    """User profile."""
    user = get_object_or_404(User, username=username)
    form = AvatarForm(data=request.POST)

    return render(request, 'socialaxy_chat/profile.html', {
        'profile_user': user,
        'is_current_user': user == request.user,
        'form': form,
    })


@login_required
def thread_view(request, username=None, thread_id=None):
    """Thread page."""
    interlocutor = None
    if username:
        interlocutor = get_object_or_404(User, username=username)
        thread = Thread.objects \
            .annotate(count=Count('users')) \
            .filter(users=request.user) \
            .filter(users=interlocutor) \
            .filter(count=2) \
            .first()
        if not thread:
            thread = Thread(name=', '.join([request.user.username, username]))
            thread.save()
            thread.users.add(request.user, interlocutor)
    elif thread_id:
        thread = get_object_or_404(Thread, pk=thread_id)
    else:
        # username or thread_id should be passed.
        raise Http404

    # The user visited this tread - delete user's unread thread.
    UnreadThread.objects.filter(thread=thread, user=request.user).delete()

    users = {}
    for user in thread.users.all():
        profile, _ = Profile.objects.get_or_create(user=user)
        users[user.pk] = {
            'username': user.username,
            'avatar': profile.avatar.url,
        }

    messages = Message.objects.select_related('user').filter(thread=thread) \
                   .order_by('date')[:50]
    for message in messages:
        if message.user.pk not in users:
            try:
                avatar = message.user.profile.avatar.url
            except Profile.DoesNotExist:
                # If there no user profile - create it.
                profile, _ = Profile.objects.get_or_create(user=message.user)
                avatar = profile.avatar.url

            users[message.user.pk] = {
                'username': message.user.username,
                'avatar': avatar,
            }
    for message in messages:
        message.avatar = users[message.user.pk]['avatar']

    return render(request, 'socialaxy_chat/thread.html', {
        'thread': thread,
        'messages': messages,
        'users': users,
        'interlocutor': interlocutor,
    })


@login_required
def update_profile(request):
    """Update user."""
    if request.method == 'POST':
        avatar = request.FILES.get('avatar', '')
        if avatar:
            profile = get_object_or_404(Profile, user=request.user)
            form = AvatarForm(request.POST, request.FILES, instance=profile)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            allowed_fields = ['first_name', 'last_name', 'email']
            field = request.POST.get('name', '')
            value = request.POST.get('value', '')
            if field and field in allowed_fields:
                setattr(request.user, field, value)
                try:
                    request.user.clean_fields()
                    request.user.save()
                    return JsonResponse({'success': True})
                except ValidationError as e:
                    return JsonResponse(
                        ', '.join(e.message_dict[field]),
                        safe=False,
                        status=422
                    )

    return JsonResponse(
        _("You can't change this field"),
        safe=False,
        status=403
    )


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('socialaxy_chat:user_list'))

    return render(request, 'socialaxy_chat/login.html', {'form': form})


@login_required
def log_out(request):
    logout(request)
    return redirect(reverse('socialaxy_chat:login'))


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)

            return redirect(reverse('socialaxy_chat:user_list'))

    return render(request, 'socialaxy_chat/signup.html', {'form': form})

socialaxy_site/templates/socialaxy_chat/base_copy.html
{% load static from staticfiles %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="robots" content="none">
    <link href="{% static 'socialaxy_chat/images/icon32.png' %}" rel="icon"/>
    <link rel="stylesheet" type="text/css" href="{% static 'socialaxy_chat/style/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'socialaxy_chat/style/main.css' %}?v=2"/>
    {% block css %}{% endblock css %}
    <title>{% block title %}{% trans "Chat room" %}{% endblock title %}</title>
</head>
<body style="background-image:url({% static 'socialaxy_chat/images/bg.jpg' %});">
<header id="header" class="cover" role="banner"
            style="background-image:url({% static 'socialaxy_chat/images/bg.jpg' %});"
            data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
</header>
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar"
            aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'socialaxy_chat:user_list' %}">{% trans "Chat" %}</a>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            {% url 'socialaxy_chat:user_list' as user_list_url %}
            <li class="nav-item {% if request.get_full_path == user_list_url %}active{% endif %}">
                <a class="nav-link" href="{{ user_list_url }}">{% trans "Home" %} <span
                        class="sr-only">({% trans "current" %})</span></a>
            </li>
        </ul>
        <ul class="navbar-nav mr-right">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <svg class="icon">
                            <use xlink:href="#chat-icon"/>
                        </svg>
                        {% if unread_threads %}
                            <span class="badge badge-pill badge-danger">{{ unread_threads }}</span>{% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        {% for thread in threads %}
                            <a class="dropdown-item"
                               href="{% url 'socialaxy_chat:thread' thread.0 %}">{{ thread.1 }}</a>
                        {% endfor %}
                    </div>
                </li>
                {% url 'socialaxy_chat:user' user.username as user_url %}
                <li class="nav-item {% if request.get_full_path == user_url %}active{% endif %}">
                    <a class="nav-link" href="{{ user_url }}">
                        <img src="{{ user.profile.avatar.url }}" height="20" width="20" alt="avatar">
                        {{ user.username }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'socialaxy_chat:logout' %}">{% trans "Log out" %}</a>
                </li>
            {% else %}
                {% url 'socialaxy_chat:signup' as signup_url %}
                <li class="nav-item {% if request.path == signup_url %}active{% endif %}">
                    <a class="nav-link" href="{{ signup_url }}">{% trans "Sign up" %}</a>
                </li>
                {% url 'socialaxy_chat:login' as login_url %}
                <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                    <a class="nav-link" href="{{ login_url }}">{% trans "Log in" %}</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock content %}
</div>
<script type="text/javascript" src="{% static 'socialaxy_chat/script/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'socialaxy_chat/script/tether.min.js' %}"></script>
<script type="text/javascript" src="{% static 'socialaxy_chat/script/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'socialaxy_chat/script/bootstrap-editable.min.js' %}"></script>
{% block script %}{% endblock script %}
</body>
</html>

socialaxy_site/templates/socialaxy_chat/login.html
{% extends 'socialaxy_chat/base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div>
        <form action="{% url 'socialaxy_chat:login' %}" method="post" class="">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            {% for field in form %}
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field|add_class:"form-control" }}
                        {% if field.errors %}
                            <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary float-right">{% trans "Log in" %}</button>
        </form>


        <a href="{% url 'social:begin' 'facebook' %}">{% trans "Login with Facebook" %}</a>
        <p>{% trans "Don't have an account?" %} <a href="{% url 'socialaxy_chat:signup' %}">{% trans "Sign up!" %}</a>
        </p>
    </div>
{% endblock content %}

socialaxy_site/templates/socialaxy_chat/main_page.html
{% extends 'socialaxy_chat/base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Profile" %}{% endblock title %}

{% block content %}
<div class="jumbotron bg-white mt-5">
<div class="row my-2">
        <div class="col-lg-8 push-lg-4">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">{% trans "Profile" %}</a>
                </li>
                <li class="nav-item">
                    {% if is_current_user %}
                    <a href="" data-target="#chats" data-toggle="tab" class="nav-link">{% trans "Chats" %}</a>
                    {% else %}
                    <a href="{% url 'socialaxy_chat:chat' profile_user.username %}" class="name nav-link text-muted">{% trans "Chat" %}</a>
                    {% endif %}
                </li>
            </ul>
            <div class="tab-content p-b-3">
                <div class="tab-pane active" id="profile">
                    <h4 class="my-2">{% trans "User Profile" %}</h4>
                    <div class="row">
                        <div class="col-md-12 mt-3">
                            <div class="form-group row">
                                <div class="col-md-4 float-left"><h6>{% trans "First name" %}</h6></div>
                                <div class="col-md-8 float-right">
                                    {% if is_current_user %}
                                    <a href="#" id="first_name" class="editable" data-type="text" data-pk="first_name" data-url="{% url 'socialaxy_chat:update_profile' %}" data-placeholder="{% trans 'Enter first name' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.first_name }}</a>
                                    {% else %}
                                    {{ profile_user.first_name }}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-4 float-left"><h6>{% trans "Last name" %}</h6></div>
                                <div class="col-md-8 float-right">
                                    {% if is_current_user %}
                                    <a href="#" id="last_name" class="editable" data-type="text" data-pk="last_name" data-url="{% url 'socialaxy_chat:update_profile' %}" data-placeholder="{% trans 'Enter last name' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.last_name }}</a>
                                    {% else %}
                                    {{ profile_user.last_name }}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-4 float-left"><h6>{% trans "Email" %}</h6></div>
                                <div class="col-md-8 float-right">
                                    {% if is_current_user %}
                                    <a href="#" id="email" class="editable" data-type="email" data-pk="email" data-url="{% url 'socialaxy_chat:update_profile' %}" data-placeholder="{% trans 'Enter email' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.email }}</a>
                                    {% else %}
                                    {{ profile_user.email }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/row-->
                </div>
                {% if is_current_user %}
                <div class="tab-pane" id="chats">
                    <h4 class="my-2">{% trans "Last chats" %}</h4>
                    <table class="table table-hover table-striped">
                        <tbody>
                             {% for thread in threads %}
                             <tr><td>
                                 <a href="{% url 'socialaxy_chat:thread' thread.0 %}" class="name text-muted">{{ thread.1 }}</a>
                             </td></tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-4 pull-lg-8 text-center">
            <img src="{{ profile_user.profile.avatar.url }}" class="m-x-auto img-fluid rounded-circle" alt="avatar">
            {% if is_current_user %}
            <h6 class="mt-2">{% trans "Upload a different photo" %}</h6>
            <form action="{% url 'socialaxy_chat:update_profile' %}" method="post" enctype="multipart/form-data" id="avatar-upload">
                {% csrf_token %}
                    {% for field in form %}
                        <label class="custom-file text-left">
                            {{ field|add_class:"custom-file-input" }}
                            <span class="custom-file-control"></span>
                        </label>
                    {% if field.errors %}
                        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
                          {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
            </form>
            {% endif %}
        </div>
    </div>
  </div>
{% endblock content %}

{% block script %}
  <script>
      // Set up and initialize editable.
      $.fn.editable.defaults.mode = 'inline';
      $('.editable').editable();

      $('#avatar-upload').change(function() {
          $(this).submit();
      });
  </script>
{% endblock script %}

socialaxy_site/templates/socialaxy_chat/message.html
{% url 'socialaxy_chat:user' message.user.username as user_url %}
<li id="message-{{ message.pk }}"
    class="{% if user.pk == message.user.pk %}right{% else %}left{% endif %} clearfix message {% if not message %}hidden-xs-up{% endif %}">
    <span class="chat-img">
        <a href="{{ user_url }}">
            <img src="{{ message.avatar }}" width="50" height="50" alt="User Avatar" class="avatar"/>
        </a>
    </span>
    <div class="chat-body clearfix">
        <div class="header">
            <a href="{{ user_url }}" class="text-muted profile-link">
                <strong class="username primary-font">{{ message.user.username }}</strong>
            </a>
            <small class="text-muted date-wrapper">
                <time class="date" datetime="{{ message.date }}">{{ message.date|timesince }}</time>
                ago
            </small>
        </div>
        <p class="text">{{ message.text }}</p>
    </div>
</li>

socialaxy_site/templates/socialaxy_chat/user_list.html
{% extends 'socialaxy_chat/base.html' %}
{% load i18n %}

{% block title %}{% trans "Users" %}{% endblock title %}

{% block content %}
    <div>
        <ul class="list-group">
            {% for user in users %}
                <li data-username="{{ user.username }}" class="list-group-item justify-content-between">
                    <a href="{% url 'socialaxy_chat:chat' user.username %}"
                       class="name text-muted">{{ user.username }}</a>
                    <span class="status badge badge-default badge-pill {% if user.status %}badge-success{% endif %}">
          <a href="{% url 'socialaxy_chat:user' user.username %}" class="text-white">
            {% if user.status %}Online{% else %}Offline{% endif %}
          </a>
        </span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

{% block script %}
    <script>
        var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
        var socket = new WebSocket(protocol + '://' + window.location.host + '/ws/users/');

        socket.onopen = function open() {
            console.log('WebSockets connection created.');
        };

        socket.onmessage = function message(event) {
            var data = JSON.parse(event.data);
            // NOTE: We escape JavaScript to prevent XSS attacks.
            var username = encodeURI(data['username']);
            var $user = $('li').filter(function () {
                return $(this).data('username') == username;
            });

            $user.find('.name').text(username);
            if (data['is_logged_in']) {
                $user.find('.status').addClass('badge-success').text('Online');
            }
            else {
                $user.find('.status').removeClass('badge-success').text('Offline');
            }
        };

        if (socket.readyState == WebSocket.OPEN) {
            socket.onopen();
        }
    </script>
{% endblock script %}