socialaxy_chat/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import log_in, log_out, sign_up, user_list, thread_view, call_view, profile_view, update_profile

urlpatterns = [
    url(r'^login$', log_in, name='login'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^signup$', sign_up, name='signup'),
    url(r'^$', user_list, name='user_list'),
    url(r'^user/(?P<username>.+)$', profile_view, name='user'),
    url(r'^chat/(?P<username>.+)$', thread_view, name='chat'),
    url(r'^thread/(?P<thread_id>.+)$', thread_view, name='thread'),
    url(r'^call/(?P<username>.+)$', call_view, name='call'),
    url(r'^update-profile$', update_profile, name='update_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

socialaxy_site/socialaxy_chat/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import log_in, log_out, sign_up, user_list, thread_view, profile_view, update_profile

urlpatterns = [
    url(r'^login$', log_in, name='login'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^signup$', sign_up, name='signup'),
    url(r'^$', user_list, name='user_list'),
    url(r'^user/(?P<username>.+)$', profile_view, name='user'),
    url(r'^chat/(?P<username>.+)$', thread_view, name='chat'),
    url(r'^thread/(?P<thread_id>.+)$', thread_view, name='thread'),
    url(r'^update-profile$', update_profile, name='update_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

socialaxy_site/socialaxy_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('socialaxy_chat.urls', namespace='socialaxy_chat')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

socialaxy_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('socialaxy_chat.urls', namespace='socialaxy_chat')),
    url(r'^', include('socialaxy_coming_soon_page.urls', namespace='socialaxy_coming_soon')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

socialaxy_site/socialaxy_chat/models.py
import datetime

from django.conf import settings
from django.db import models
from django.core.cache import cache
from channels.binding.websockets import WebsocketBinding


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='profile')
    avatar = models.ImageField(
        upload_to='avatars/',
        default='avatars/no-avatar.png'
    )

    def last_seen(self):
        return cache.get('seen_%s' % self.user.username)

    def online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            return now < self.last_seen() + datetime.timedelta(seconds=settings.USER_ONLINE_TIMEOUT)

        return False

    def __str__(self):
        return u'%s' % (
            self.user.username,
        )


class Thread(models.Model):
    name = models.CharField(max_length=255)
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='threads'
    )
    last_message = models.DateTimeField(null=True)

    def __str__(self):
        return u'%s' % (
            self.name,
        )


class UnreadThread(models.Model):
    thread = models.ForeignKey(Thread)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='unread_thread'
    )
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return u'%s:%s' % (
            self.thread.name,
            self.user.username,
        )


class Message(models.Model):
    thread = models.ForeignKey(Thread, related_name='messages')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.thread.last_message = datetime.datetime.now()
        self.thread.save()
        super(Message, self).save(force_insert=False, force_update=False,
                                  using=None, update_fields=None)

    def __str__(self):
        return u'%s: %s' % (
            self.user.username,
            self.text[:100],
        )


class MessageBinding(WebsocketBinding):
    model = Message
    stream = 'messages'
    fields = ['__all__']

    @classmethod
    def group_names(cls, instance):
        return ['thread-%s' % instance.thread.pk]

    def has_permission(self, user, action, pk):
        return user in self.users

socialaxy_site/socialaxy_chat/forms.py
from django import forms
from .models import Profile


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar',)

socialaxy_chat/views.py
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from django.http import JsonResponse, HttpResponseRedirect, Http404
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from .models import Profile, Thread, UnreadThread, Message
from .forms import AvatarForm

User = get_user_model()


@login_required
def user_list(request):
    """User list."""
    users = User.objects.exclude(id=request.user.id).select_related('profile')
    for user in users:
        try:
            user.status = user.profile.online()
        except Profile.DoesNotExist:
            Profile.objects.get_or_create(user=user)
            user.status = False

    return render(request, 'socialaxy_chat/user_list.html', {'users': users})


@login_required
def profile_view(request, username):
    """User profile."""
    user = get_object_or_404(User, username=username)
    form = AvatarForm(data=request.POST)

    return render(request, 'socialaxy_chat/profile.html', {
        'profile_user': user,
        'is_current_user': user == request.user,
        'form': form,
    })


@login_required
def thread_view(request, username=None, thread_id=None):
    """Thread page."""
    interlocutor = None
    if username:
        interlocutor = get_object_or_404(User, username=username)
        thread = Thread.objects \
            .annotate(count=Count('users')) \
            .filter(users=request.user) \
            .filter(users=interlocutor) \
            .filter(count=2) \
            .first()
        if not thread:
            thread = Thread(name=', '.join([request.user.username, username]))
            thread.save()
            thread.users.add(request.user, interlocutor)
    elif thread_id:
        thread = get_object_or_404(Thread, pk=thread_id)
    else:
        # username or thread_id should be passed.
        raise Http404

    # The user visited this tread - delete user's unread thread.
    UnreadThread.objects.filter(thread=thread, user=request.user).delete()

    users = {}
    for user in thread.users.all():
        profile, _ = Profile.objects.get_or_create(user=user)
        users[user.pk] = {
            'username': user.username,
            'avatar': profile.avatar.url,
        }

    messages = Message.objects.select_related('user').filter(thread=thread) \
                   .order_by('date')[:50]
    for message in messages:
        if message.user.pk not in users:
            try:
                avatar = message.user.profile.avatar.url
            except Profile.DoesNotExist:
                # If there no user profile - create it.
                profile, _ = Profile.objects.get_or_create(user=message.user)
                avatar = profile.avatar.url

            users[message.user.pk] = {
                'username': message.user.username,
                'avatar': avatar,
            }
    for message in messages:
        message.avatar = users[message.user.pk]['avatar']

    return render(request, 'socialaxy_chat/thread.html', {
        'thread': thread,
        'messages': messages,
        'users': users,
        'interlocutor': interlocutor,
    })


@login_required
def call_view(request, username):
    """Call page."""
    interlocutor = get_object_or_404(User, username=username)

    return render(request, 'socialaxy_chat/call.html', {
        'interlocutor': interlocutor,
    })


@login_required
def update_profile(request):
    """Update user."""
    if request.method == 'POST':
        avatar = request.FILES.get('avatar', '')
        if avatar:
            profile = get_object_or_404(Profile, user=request.user)
            form = AvatarForm(request.POST, request.FILES, instance=profile)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            allowed_fields = ['first_name', 'last_name', 'email']
            field = request.POST.get('name', '')
            value = request.POST.get('value', '')
            if field and field in allowed_fields:
                setattr(request.user, field, value)
                try:
                    request.user.clean_fields()
                    request.user.save()
                    return JsonResponse({'success': True})
                except ValidationError as e:
                    return JsonResponse(
                        ', '.join(e.message_dict[field]),
                        safe=False,
                        status=422
                    )

    return JsonResponse(
        _("You can't change this field"),
        safe=False,
        status=403
    )


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('socialaxy_chat:user_list'))

    return render(request, 'socialaxy_chat/login.html', {'form': form})


@login_required
def log_out(request):
    logout(request)
    return redirect(reverse('socialaxy_chat:login'))


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)

            return redirect(reverse('socialaxy_chat:user_list'))

    return render(request, 'socialaxy_chat/signup.html', {'form': form})

socialaxy_site/socialaxy_chat/views.py
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from django.http import JsonResponse, HttpResponseRedirect, Http404
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from .models import Profile, Thread, UnreadThread, Message
from .forms import AvatarForm

User = get_user_model()


@login_required
def user_list(request):
    """User list."""
    users = User.objects.exclude(id=request.user.id).select_related('profile')
    for user in users:
        try:
            user.status = user.profile.online()
        except Profile.DoesNotExist:
            Profile.objects.get_or_create(user=user)
            user.status = False

    return render(request, 'socialaxy_chat/user_list.html', {'users': users})


@login_required
def profile_view(request, username):
    """User profile."""
    user = get_object_or_404(User, username=username)
    form = AvatarForm(data=request.POST)

    return render(request, 'socialaxy_chat/profile.html', {
        'profile_user': user,
        'is_current_user': user == request.user,
        'form': form,
    })


@login_required
def thread_view(request, username=None, thread_id=None):
    """Thread page."""
    interlocutor = None
    if username:
        interlocutor = get_object_or_404(User, username=username)
        thread = Thread.objects \
            .annotate(count=Count('users')) \
            .filter(users=request.user) \
            .filter(users=interlocutor) \
            .filter(count=2) \
            .first()
        if not thread:
            thread = Thread(name=', '.join([request.user.username, username]))
            thread.save()
            thread.users.add(request.user, interlocutor)
    elif thread_id:
        thread = get_object_or_404(Thread, pk=thread_id)
    else:
        # username or thread_id should be passed.
        raise Http404

    # The user visited this tread - delete user's unread thread.
    UnreadThread.objects.filter(thread=thread, user=request.user).delete()

    users = {}
    for user in thread.users.all():
        profile, _ = Profile.objects.get_or_create(user=user)
        users[user.pk] = {
            'username': user.username,
            'avatar': profile.avatar.url,
        }

    messages = Message.objects.select_related('user').filter(thread=thread) \
                   .order_by('date')[:50]
    for message in messages:
        if message.user.pk not in users:
            try:
                avatar = message.user.profile.avatar.url
            except Profile.DoesNotExist:
                # If there no user profile - create it.
                profile, _ = Profile.objects.get_or_create(user=message.user)
                avatar = profile.avatar.url

            users[message.user.pk] = {
                'username': message.user.username,
                'avatar': avatar,
            }
    for message in messages:
        message.avatar = users[message.user.pk]['avatar']

    return render(request, 'socialaxy_chat/thread.html', {
        'thread': thread,
        'messages': messages,
        'users': users,
        'interlocutor': interlocutor,
    })


@login_required
def update_profile(request):
    """Update user."""
    if request.method == 'POST':
        avatar = request.FILES.get('avatar', '')
        if avatar:
            profile = get_object_or_404(Profile, user=request.user)
            form = AvatarForm(request.POST, request.FILES, instance=profile)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            allowed_fields = ['first_name', 'last_name', 'email']
            field = request.POST.get('name', '')
            value = request.POST.get('value', '')
            if field and field in allowed_fields:
                setattr(request.user, field, value)
                try:
                    request.user.clean_fields()
                    request.user.save()
                    return JsonResponse({'success': True})
                except ValidationError as e:
                    return JsonResponse(
                        ', '.join(e.message_dict[field]),
                        safe=False,
                        status=422
                    )

    return JsonResponse(
        _("You can't change this field"),
        safe=False,
        status=403
    )


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('socialaxy_chat:user_list'))

    return render(request, 'socialaxy_chat/login.html', {'form': form})


@login_required
def log_out(request):
    logout(request)
    return redirect(reverse('socialaxy_chat:login'))


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)

            return redirect(reverse('socialaxy_chat:user_list'))

    return render(request, 'socialaxy_chat/signup.html', {'form': form})

templates/socialaxy_chat/base.html
{% load static from staticfiles %}
{% load i18n %}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title>Socialaxy</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Socialaxy - social galaxy, new startup."/>
    <meta name="keywords" content="socialaxy, social galaxy, social network"/>
    <meta name="author" content="Shevchenko Vlad"/>

    <link href="{% static 'socialaxy_chat/images/icon64.png' %}" rel="icon"/>

    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'socialaxy_chat/style/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'socialaxy_chat/style/icomoon.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'socialaxy_chat/style/bootstrap.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'socialaxy_chat/style/style.css' %}">

    <!-- Modernizr JS -->
    <script type="text/javascript" src="{% static 'socialaxy_chat/script/modernizr-2.6.2.min.js' %}"></script>

</head>
<body>

<div class="loader"></div>

<div id="page">
    <header id="header" class="cover" role="banner" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="text-center">
                    <div class="animate-box logo">
                        <a href="{% url 'socialaxy_chat:user_list' %}">
                            <img src="{% static 'socialaxy_chat/images/logo1600.png' %}" alt="logo"/>
                        </a>
                    </div>
                </div>
                {% block content %}{% endblock content %}
            </div>
        </div>
    </header>

    <footer id="footer" role="contentinfo">
        <div class="container">
            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p>
                        <small class="block">&copy; 2017 All Rights Reserved.</small>
                    </p>
                </div>
            </div>

        </div>
    </footer>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>

<!-- jQuery -->
<script type="text/javascript" src="{% static 'socialaxy_chat/script/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script type="text/javascript" src="{% static 'socialaxy_chat/script/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script type="text/javascript" src="{% static 'socialaxy_chat/script/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script type="text/javascript" src="{% static 'socialaxy_chat/script/jquery.waypoints.min.js' %}"></script>

<!-- Stellar -->
<script type="text/javascript" src="{% static 'socialaxy_chat/script/jquery.stellar.min.js' %}"></script>

<!-- Count Down -->
<script type="text/javascript" src="{% static 'socialaxy_chat/script/simplyCountdown.js' %}"></script>
<!-- Main -->
<script type="text/javascript" src="{% static 'socialaxy_chat/script/main.js' %}"></script>

<script>
    var d = new Date(new Date().getTime() + 800 * 120 * 120 * 2000);

    // default example
    simplyCountdown('.simply-countdown-one', {
        year: d.getFullYear(),
        month: d.getMonth() + 1,
        day: d.getDate()
    });

    //jQuery example
    $('#simply-countdown-losange').simplyCountdown({
        year: d.getFullYear(),
        month: d.getMonth() + 1,
        day: d.getDate(),
        enableUtc: false
    });
</script>

</body>
</html>

templates/socialaxy_chat/login.html
{% extends 'socialaxy_chat/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="col-md-8 col-md-offset-2 text-center">
        <div class="display-t">
            <div class="planet-bg"></div>
            <div class="display-tc animate-box" data-animate-effect="fadeIn">
                <div class="mt-5">
                    <form action="{% url 'socialaxy_chat:login' %}" method="post" class="">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        {% for field in form %}
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">{{ field.label }}</label>
                                <div class="col-sm-9">
                                    {{ field|add_class:"form-control" }}
                                    {% if field.errors %}
                                        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
                                            {{ field.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary float-right">{% trans "Log in" %}</button>
                    </form>


                    <a href="{% url 'social:begin' 'facebook' %}"><i class="icon-facebook-with-circle"></i></a>
                    <a href="{% url 'social:begin' 'github' %}"><i class="icon-github-with-circle"></i></a>
                    <a href="{% url 'social:begin' 'twitter' %}"><i class="icon-twitter-with-circle"></i></a>
                    <p>{% trans "Don't have an account?" %} <a
                            href="{% url 'socialaxy_chat:signup' %}">{% trans "Sign up!" %}</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/socialaxy_chat/message.html
{% url 'socialaxy_chat:user' message.user.username as user_url %}
<li id="message-{{ message.pk }}" class="{% if user.pk == message.user.pk %}right{% else %}left{% endif %} clearfix message {% if not message %}hidden-xs-up{% endif %}">
    <span class="chat-img">
        <a href="{{ user_url }}">
            <img src="{{ message.avatar }}" width="50" height="50" alt="User Avatar" class="avatar" />
        </a>
    </span>
    <div class="chat-body clearfix">
        <div class="header">
            <a href="{{ user_url }}" class="text-muted profile-link">
                <strong class="username primary-font">{{ message.user.username }}</strong>
            </a>
            <small class="text-muted date-wrapper"><time class="date" datetime="{{ message.date }}">{{ message.date|timesince }}</time> ago</small>
        </div>
        <p class="text">{{ message.text }}</p>
    </div>
</li>

templates/socialaxy_chat/signup.html
{% extends 'socialaxy_chat/base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
  <div class="jumbotron mt-5">
  <form action="{% url 'socialaxy_chat:signup' %}" method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
      {{ form.non_field_errors }}
    </div>
    {% endif %}
    {% for field in form %}
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">{{ field.label }}</label>
        <div class="col-sm-9">
        {{ field|add_class:"form-control" }}
        </div>
        {% if field.errors %}
        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
          {{ field.errors }}
        </div>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary float-right">{% trans "Sign up" %}</button>
    <p>{% trans "Already have an account?" %} <a href="{% url 'socialaxy_chat:login' %}">{% trans "Log in!" %}</a></p>
  </form>
  </div>
{% endblock content %}

templates/socialaxy_chat/thread.html
{% extends 'socialaxy_chat/base.html' %}
{% load i18n %}

{% block title %}{% trans "Tread" %} {{ thread.name }}{% endblock title %}

{% block content %}
    <div class="jumbotron thread-jumbotron bg-white">
        <div class="conversation">
            <div class="row">
                <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="clearfix">
                                {{ thread.name }}{% if interlocutor %}
                                    <a href="{% url 'socialaxy_chat:call' interlocutor.username %}"
                                       class="h2 float-right">☎</a>
                                {% endif %}
                            </h4>
                        </div>
                        <div id="chat-body" class="panel-body bg-faded p-2">
                            <ul id="messages" class="chat">
                                {% include "socialaxy_chat/message.html" %}
                                {% for message in messages %}
                                    {% include "socialaxy_chat/message.html" %}
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="panel-footer">
                            <div class="input-group">
                                <input id="btn-input" type="text" class="form-control input-sm"
                                       placeholder="Type your message here..."/>
                                <span class="input-group-btn">
                                <button class="btn btn-warning btn-sm" id="btn-chat">
                                    Send</button>
                            </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block script %}
<script>
    var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
    var socket = new WebSocket(protocol + '://' + window.location.host + '/ws/thread/' + {{ thread.id }});
    var users = {% autoescape off %}{{ users }}{% endautoescape %};
    var user = {{ user.pk }};
    var $input = $('#btn-input');
    var $chat = $('#chat-body');
    var $message;

    function sendMessage() {
        socket.send(JSON.stringify({
            text: $input.val()
        }));
        $input.val('');
    }

    $chat.scrollTop($chat.prop('scrollHeight'));

    $('#btn-chat').click(sendMessage);
    $input.keypress(function (e) {
        if (e.which == 13) {
            sendMessage();
        }
    });

    socket.onopen = function open() {
        console.log('WebSockets connection created.');
    };

    socket.onmessage = function message(event) {
        var raw_data = JSON.parse(event.data);
        var action = raw_data.payload.action;
        var data = raw_data.payload.data;
        var pk = raw_data.payload.pk;

        // On message Update.
        if (action == 'update') {
            $message = $('#message-' + pk);
            $message.find('.text').text(data.text);
        }

        // On message Insert.
        if (action == 'create') {
            $message = $('#message-').clone().toggleClass('left', data.user != user).toggleClass('right', data.user == user).removeClass('hidden-xs-up').attr('id', 'message-' + pk).appendTo('#messages');
            $message.find('.text').text(data.text);
            $message.find('.date').data('date', data.date).text('{% trans "Just now" %}');
            if (users.hasOwnProperty(data.user)) {
                // TODO [Mike] Need to think how to improve this.
                $message.find('.profile-link').attr('href', '/user/' + users[data.user].username);
                $message.find('.username').text(users[data.user].username);
                $message.find('.avatar').attr('src', users[data.user].avatar);
            }

            // Confirm that message was read.
            socket.send(JSON.stringify({
                read: true,
            }));
        }

        // On message Delete.
        if (action == 'delete') {
            $('#message-' + pk).remove();
        }
        $chat.scrollTop($chat.prop('scrollHeight'));
    };

    if (socket.readyState == WebSocket.OPEN) {
        socket.onopen();
    }
</script>
{% endblock script %}

templates/socialaxy_chat/user_list.html
{% extends 'socialaxy_chat/base.html' %}
{% load i18n %}

{% block title %}{% trans "Users" %}{% endblock title %}

{% block content %}
      <div class="jumbotron bg-white mt-5">

  <ul class="list-group">
    {% for user in users %}
      <li data-username="{{ user.username }}" class="list-group-item justify-content-between">
        <a href="{% url 'socialaxy_chat:chat' user.username %}" class="name text-muted">{{ user.username }}</a>
        <span class="status badge badge-default badge-pill {% if user.status %}badge-success{% endif %}">
          <a href="{% url 'socialaxy_chat:user' user.username %}" class="text-white">
            {% if user.status %}Online{% else %}Offline{% endif %}
          </a>
        </span>
      </li>
    {% endfor %}
  </ul>
  </div>
{% endblock content %}

{% block script %}
  <script>
    var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
    var socket = new WebSocket(protocol + '://' + window.location.host + '/ws/users/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      var username = encodeURI(data['username']);
      var $user = $('li').filter(function () {
        return $(this).data('username') == username;
      });

      $user.find('.name').text(username);
      if (data['is_logged_in']) {
        $user.find('.status').addClass('badge-success').text('Online');
      }
      else {
        $user.find('.status').removeClass('badge-success').text('Offline');
      }
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}